[package]
name = "spire-plugin"
version = "0.0.0"
authors = ["Konge <zkonge@outlook.com>"]
edition = "2021"

[dependencies]
prost = "0.12.4"
prost-types = "0.12.4"
tonic = "0.11.0"

[build-dependencies]
tonic-build = "0.11.0"

[features]
default = [
    "agent-keymanager",
    "agent-nodeattestor",
    "agent-svidstore",
    "agent-workloadattestor",

    "server-bundlepublisher",
    "server-credentialcomposer",
    "server-keymanager",
    "server-nodeattestor",
    "server-notifier",
    "server-upstreamauthority",
]

agent-keymanager = []
agent-nodeattestor = []
agent-svidstore = []
agent-workloadattestor = []

server-bundlepublisher = []
server-credentialcomposer = []
server-keymanager = []
server-nodeattestor = []
server-notifier = []
server-upstreamauthority = []
