[package]
name = "dummy-workload-attestor"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.1", features = ["rt"] }
pluginx = { git = "https://github.com/zkonge/pluginx.git" }
spire-plugin = { path = "../../" }
