[package]
name = "dummy-node-attestor"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36.0", features = ["rt", "macros"] }
pluginx = { git = "https://github.com/zkonge/pluginx.git" }
spire-plugin = { git = "../" }
futures = { version = "0.3.30", default-features = false }
hcl-rs = "0.16.7"
serde = { version = "1.0.197", features = ["derive"] }
