[package]
name = "dummy-node-attestor"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
futures-util.workspace = true
pluginx.workspace = true
spire-plugin.workspace = true

hcl-rs = "0.19.4"
serde = { version = "1.0.228", features = ["derive"] }

[[bin]]
name = "dummy-node-attestor-server"
path = "src/bin/server.rs"

[[bin]]
name = "dummy-node-attestor-agent"
path = "src/bin/agent.rs"
