[package]
name = "dummy-workload-attestor-host"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
futures-util.workspace = true
pluginx.workspace = true
spire-plugin.workspace = true